<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://127.0.0.1:8000/soap/client/register"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="clients" targetNamespace="http://127.0.0.1:8000/soap/client/register">
    <types>
        <xsd:schema targetNamespace="http://127.0.0.1:8000/soap/client/register"/>
    </types>
    <portType name="clientsPort">
        <operation name="register">
            <documentation>register</documentation>
            <input message="tns:registerIn"/>
            <output message="tns:sendResponse"/>
        </operation>
    </portType>
    <binding name="clientsBinding" type="tns:clientsPort">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="register">
            <soap:operation soapAction="http://127.0.0.1:8000/soap/client/register#register"/>
            <input>
                <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://127.0.0.1:8000/soap/client/register"/>
            </input>
        </operation>
    </binding>
    <service name="clientsService">
        <port name="clientsPort" binding="tns:clientsBinding">
            <soap:address location="http://127.0.0.1:8000/soap/client/register"/>
        </port>
    </service>
    <message name="registerIn">
        <part name="document" type="xsd:anyType"/>
        <part name="name" type="xsd:anyType"/>
        <part name="email" type="xsd:anyType"/>
        <part name="phone" type="xsd:anyType"/>
    </message>
    <message name="sendResponse">
        <part name="return" type="xsd:string"/>
    </message>
</definitions>
