version: "3.4"

services:
  symfony-web-application:
    build:
      context: .
      target: symfony-web-application
    volumes:
      - .:/app
    stop_grace_period: 0s
    ports:
      - 8000:8000
